Added output for docker pull
getpopper/popper pull request #945
Opened 2020-12-02 23:11 UTC by michaelroyzen

Resolves #892. @ivotron your feedback would be appreciated.

2020-12-06 21:35 UTC, ivotron requested changes
thanks a lot @michaelroyzen , this looks great. Please take a look at the feedback

2020-12-06 21:35 UTC, ivotron commented on src/popper/runner_host.py
> +                            log.step_info(f"[{step.id}] " + chunk['id'] + ': ' + chunk['status'])
to be consistent with the way logging is done in other places, this can ommit the `[{step.id}] ` prefix and log the output directly

2020-12-06 21:35 UTC, ivotron commented on src/popper/runner_host.py
> +                log.step_info(f"[{step.id}] {img}:{tag}")
this line can be omitted, as the last line from docker pull is something like `Downloaded newer image for <url>:<tag>` so it is already informing about what got downloaded

2020-12-06 21:35 UTC, ivotron commented on src/popper/runner_host.py
> +                            log.step_info(f"[{step.id}] " + chunk['status'])
similarly, the `[{step.id}] ` prefix can be omitted

2020-12-07 00:26 UTC, michaelroyzen commented
Thanks for the feedback. I've made the changes, please let me know if there is anything else I should do.

2020-12-12 15:36 UTC, merged

2020-12-12 15:37 UTC, ivotron commented
thanks a lot @michaelroyzen! 🙏